//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Eczane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLILETISIM
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Ad Alaný Boþ Geçilemez  ... ")]
        public string AD { get; set; }

        [Required(ErrorMessage = "Mail Alaný Boþ Geçilemez  ... ")]
        public string MAIL { get; set; }
        public string KONU { get; set; }
        public string Mesaj { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
